name: Actions Workflow


on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
         pwd
         ls -a
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: list files
        run: |
         pwd
         ls -a
 
      - name: simple js action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Terence
      - name: Log Greeting Time
        run: echo "${{ steps.greet.ouputs.time }}"